bundler_args: --binstubs
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
gemfile:
  - gemfiles/2.3.gemfile
  - gemfiles/3.1.gemfile
  - gemfiles/4.1.gemfile

matrix:
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/2.3.gemfile
    - rvm: 2.1.1
      gemfile: gemfiles/2.3.gemfile


script: "bundle exec rake test"

notifications:
  irc: "irc.freenode.org#axlsx"

